// <auto-generated />
using AntManZooApi.Datas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AntManZooApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AntManZooClassLibrary.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Species")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 6,
                            Description = "Balto le héros !",
                            ImageLink = "https://www.sciencesetavenir.fr/assets/img/2023/04/25/cover-r4x3w1200-6447e451a984d-balto-kasson.jpg",
                            Name = "Balto",
                            Species = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 12,
                            Description = "Très beau cheval de feu",
                            ImageLink = "https://i.ytimg.com/vi/vbb0oUNE65o/sddefault.jpg",
                            Name = "Ponyta",
                            Species = 4
                        },
                        new
                        {
                            Id = 3,
                            Age = 3,
                            Description = "Un ours originaire de Springfield",
                            ImageLink = "https://media.gq.com/photos/596cf8527bf9083f8bf881b8/16:9/w_1280,c_limit/winnie-the-pooh-ban-china.jpg",
                            Name = "Winnie",
                            Species = 2
                        },
                        new
                        {
                            Id = 4,
                            Age = 41,
                            Description = "Un très beau lion à qui il manque une patte",
                            ImageLink = "https://cdn.images.express.co.uk/img/dynamic/20/590x/secondary/Game-of-Thrones-Jaime-was-trapped-with-his-cousin-1864452.jpg?r=1558125976497",
                            Name = "Jamie",
                            Species = 3
                        },
                        new
                        {
                            Id = 5,
                            Age = 110,
                            Description = "Il bouffe tout",
                            ImageLink = "https://static.cnews.fr/sites/default/files/000_8vq76v_5fbcea50c8137.jpg",
                            Name = "Bouftou",
                            Species = 5
                        },
                        new
                        {
                            Id = 6,
                            Age = 2,
                            Description = "Une belle perruche dedju !",
                            ImageLink = "https://www.fermeexotique.fr/public/img/medium/nos-animaux-afrique53eb4cd7bb705.jpg",
                            Name = "Parrot",
                            Species = 6
                        });
                });

            modelBuilder.Entity("AntManZooClassLibrary.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anthony.douchet@hotmail.fr",
                            Firstname = "Anthony",
                            Lastname = "DOUCHET",
                            Password = "UEFzczEyMyEhY2zDqSBzdXBlciBzZWNyw6h0ZQ=="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
